### ISSUE TITLE
broom.glance issue in 2-dplyrXdf.rmd

### ISSUE THREAD

**Issue by joshuafennessy** [Azure/mr4ds#11]
In the final chunk of the notebook where the glance function is used to collect summary statistics of the LM function, the resulting object consists of a data frame and a list -- the list is not view able as individual columns.

See attached screenshot for example:

![broom glance](https://cloud.githubusercontent.com/assets/7947679/19282909/0f9aefc6-8fbe-11e6-9086-d4a98d1f777f.PNG)

**Comment by akzaidi** [comment]
[Fix](https://github.com/akzaidi/R-cadence/commit/a8f8fc366f09b6e86f617810b8a83b129d12cd35). Might not be the most charming fix though, I'll keep this open for now

**Comment by akzaidi** [comment]
Fixed in dplyrXdf.
